config/routes.rb
Rails.application.routes.draw do
  root to: "desired_ingredients#new"
  resources :finders, only: [:index, :show, :delete]
  resources :desired_ingredients, only: [:new, :create]
  resources :recipes
  delete 'clear_pot', to: 'desired_ingredients#clear_pot'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :recipes
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipes
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :recipes
end

app/models/desired_ingredient.rb
class DesiredIngredient < ApplicationRecord
  attr_reader :recipes

  belongs_to :finder

  validates :name, presence: true

  def recipes
    options = [
            "#{name} %",
            "#{name}s %",
            "#{name}s,%",
            "#{name},%",
            "% #{name} %",
            "% #{name}s %",
            "% #{name}s,%",
            "% #{name},%",
            "% #{name}s",
            "% #{name}"
          ]
    # regex_name = /(^|\s)#{name}($[\s,])/
    
    @recipes ||= Recipe.joins(:ingredients)
    .where(Ingredient.arel_table[:name].matches_any(options)).distinct
    # .where('ingredients.name ILIKE ?', regex_name).distinct
  end 
end

app/models/finder.rb
class Finder < ApplicationRecord
  has_many :desired_ingredients

  def all_recipes
    desired_ingredients.map(&:recipes).flatten!
  end

  # recipes in order from most relevant to the least
  def recipes_data
    all_recipes.inject({}) do |hash, recipe|
      hash[recipe] ||= 0
      hash[recipe] += 1
      hash
    end.sort_by {|k, v| -v}
  end

  def most_relevant_recipes_only
    recipes_data.map(&:first)
  end
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_and_belongs_to_many :recipes
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :cuisine
  belongs_to :category
  belongs_to :author
  has_and_belongs_to_many :ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_pot

  def current_pot
    if session[:finder_id]
      Finder.find(session[:finder_id])
    else
      Finder.new
    end
  end

  def current_pot_or_create
    cp = current_pot
    if cp.new_record?
      cp.save
      session[:finder_id] = cp.id
    end
    cp
  end
end

app/controllers/desired_ingredients_controller.rb
class DesiredIngredientsController < ApplicationController
  def new
    @desired_ingredient = DesiredIngredient.new
    if current_pot.desired_ingredients.any?
      @most_relevant_recipes = current_pot.most_relevant_recipes_only.first(20)
    end
  end

  def create
    finder = current_pot_or_create
    @desired_ingredient = finder.desired_ingredients.find_or_create_by(desired_ingredient_params)
    redirect_to new_desired_ingredient_path
  end

  def clear_pot
    session[:finder_id] = nil
    redirect_to new_desired_ingredient_path
  end

  private

  def desired_ingredient_params
    params.require(:desired_ingredient).permit(:name)
  end
end

app/controllers/finders_controller.rb
class FindersController < ApplicationController
  def index
  end

  def new
  end

  def show
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:title, :cooking_time, :prep_time, :ratings, :cuisine_id, :category_id, :author_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/desired_ingredients_helper.rb
module DesiredIngredientsHelper
end

app/helpers/finders_helper.rb
module FindersHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/desired_ingredients/new.html.erb
<h2>Find ingredients in your kitchen and see what you can cook with them</h2>
<%= form_for(@desired_ingredient, local: true) do |form| %>
  <% if @desired_ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@desired_ingredient.errors.count, "error") %> prohibited this desired_ingredient from being saved:</h2>

      <ul>
      <% @desired_ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Ingredient" %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit "Add ingredient to your pot" %>
  </div>
<% end %>


<h3>Ingredients in Your Pot:</h3>
<% if current_pot.desired_ingredients.any? %>
  <ol>
    <% current_pot.desired_ingredients.each do |ingredient| %>
      <li class="pot-item"><%= ingredient.name %></li> 
    <% end %>
  </ol>
  <%= link_to 'Clear your pot', clear_pot_path, method: :delete, class: 'button' %>

  <h3>Below are most relevant recipes based on ingredients in your pot:</h3>

  <% @most_relevant_recipes.each do |recipe| %>
    <hr>
    <%= image_tag(recipe.image, size: "100x100", alt: "#{recipe.title}") %>
    <%= link_to recipe.title, recipe %>
  <% end %>
<% end %>

app/views/finders/index.html.erb
<h1>Finders#index</h1>
<p>Find me in app/views/finders/index.html.erb</p>

app/views/finders/show.html.erb
<h1>Finders#show</h1>
<p>Find me in app/views/finders/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DinnerTime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>It's Dinner Time!</h1>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :cooking_time %>
    <%= form.number_field :cooking_time %>
  </div>

  <div class="field">
    <%= form.label :prep_time %>
    <%= form.number_field :prep_time %>
  </div>

  <div class="field">
    <%= form.label :ratings %>
    <%= form.text_field :ratings %>
  </div>

  <div class="field">
    <%= form.label :cuisine_id %>
    <%= form.text_field :cuisine_id %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id %>
  </div>

  <div class="field">
    <%= form.label :author_id %>
    <%= form.text_field :author_id %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Cooking time</th>
      <th>Prep time</th>
      <th>Ratings</th>
      <th>Cuisine</th>
      <th>Category</th>
      <th>Author</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.cooking_time %></td>
        <td><%= recipe.prep_time %></td>
        <td><%= recipe.ratings %></td>
        <td><%= recipe.cuisine %></td>
        <td><%= recipe.category %></td>
        <td><%= recipe.author %></td>
        <td><%= recipe.image %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag(@recipe.image, size: "200x200", alt: "#{@recipe.title}") %>
</p>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Cooking time:</strong>
  <%= @recipe.cooking_time %>
</p>

<p>
  <strong>Prep time:</strong>
  <%= @recipe.prep_time %>
</p>

<p>
  <strong>Ratings:</strong>
  <%= @recipe.ratings %>
</p>

<p>
  <strong>Cuisine:</strong>
  <%= @recipe.cuisine.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @recipe.category.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @recipe.author.name %>
</p>

<p>
  <ol>
    <% @recipe.ingredients.each do |ingredient| %>
      <li><%= ingredient.name %></li>
    <% end %>
  </ol>
</p>


<%= link_to 'Back', new_desired_ingredient_path, class: 'button' %>